### ISSUE TITLE
Deleting or renaming watched file results in error

### ISSUE THREAD

**Issue by marsupialmouse** [bammoo/gulp-watch-less2#2]
When a watched file containing an import statement is deleted or renamed an error is thrown and the process terminated. The error occurs on line 27 of index.js (the file has no contents, so calling .toString() fails).

Example directory structure:

```
content/less/desktop.less                   (imports about.less and home.less)
content/less/desktop/pages/about.less       (just styles, no imports)
content/less/desktop/pages/home.less        (just styles, no imports)
```

Example task:

```
gulp.task('less-watch', function () {
    return gulp
         .src(['content/less/*.less'])
         .pipe(watchLess('content/less/*.less', { verbose: true, base: 'content/less' }))
         .pipe(less())
         .pipe(gulp.dest('content/css'));
});
```

Deleting desktop.less causes the error (it should do nothing).

Renaming desktop.less causes the same error (it should compile the renamed file).

**Comment by giiska** [comment]
Is fixed, this plugin was refactored and bumped to 2.0. You can reinstall and try it.

You can use [gulp-plumber](https://github.com/floatdrop/gulp-plumber) to avoid watch process be terminated by errors. 

Example:

``` js
  return gulp.src(watchGlob)
    .pipe(plumber())
    .pipe(watchLess(watchGlob, {verbose: true})
    .pipe(less())
```
