### ISSUE TITLE
Multiple level file imports not causing recompilation

### ISSUE THREAD

**Issue by marsupialmouse** [bammoo/gulp-watch-less2#3]
When an import statement is added to a .less file that is already imported by another .less file, changes to the file imported at the deepest level do not cause recompilation of the file at the top level.

Example directory structure:

```
content/less/desktop.less                   (imports about.less and home.less)
content/less/desktop/includes/colours.less  (contains colour variables)
content/less/desktop/pages/about.less       (just styles, no imports)
content/less/desktop/pages/home.less        (just styles, no imports)
```

Example task:

```
gulp.task('less-watch', function () {
    return gulp
         .src(['content/less/*.less'])
         .pipe(watchLess('content/less/*.less', { verbose: true, base: 'content/less' }))
         .pipe(less())
         .pipe(gulp.dest('content/css'));
});
```

Steps to reproduce:
1. Change home.less to import colours.less
2. Change variable in colours.less

Step 1 should (and does) cause a recompilation of desktop.less.

Step 2 should (but doesn't) cause a recompilation of desktop.less.

**Comment by giiska** [comment]
@marsupialmouse  It's resolved at latest version. Welcome to test it.
