### ISSUE TITLE
Changes to previously imported file cause recompilation

### ISSUE THREAD

**Issue by marsupialmouse** [bammoo/gulp-watch-less2#4]
If a .less file (A) is imported by another .less file (B) which is in turn imported by the parent .less file (C), changes to A cause recompilation of C. If B is changed so that it no longer imports A, C is recompiled. If you then make a change to A, C is recompiled even though neither it nor any of its imports depend on file A.

Example directory structure:

```
content/less/desktop.less                   (imports home.less and search.less)
content/less/desktop/includes/colours.less  (contains colour variables)
content/less/desktop/pages/home.less        (just styles, no imports)
content/less/desktop/pages/search.less      (styles + import colours.less)
```

Example task:

```
gulp.task('less-watch', function () {
    return gulp
         .src(['content/less/*.less'])
         .pipe(watchLess('content/less/*.less', { verbose: true, base: 'content/less' }))
         .pipe(less())
         .pipe(gulp.dest('content/css'));
});
```

Steps to reproduce:
1. Remove the import statement from search.less
2. Make a change to colours.less.

Step 1 should (and does) cause a recompilation of desktop.less.

Step 2 should not (but does) cause a recompilation of desktop.less.

**Comment by giiska** [comment]
Maybe it's fixed as the 2.0 is more reliable on imports watch.

Can you try the new latest version to check this issue?

**Comment by marsupialmouse** [comment]
Sorry, not fixed.

**Comment by giiska** [comment]
@marsupialmouse  Please test master if the latest commit solves this issue.

**Comment by giiska** [comment]
@marsupialmouse The import test case [covers this](https://github.com/bammoo/gulp-watch-less2/blob/master/test/test-import.js) now.
